---
version: "3.7"

services:
  tf:
    working_dir: ${WORKING_DIR:-/app}
    entrypoint: ${ENTRYPOINT}
    image: hashicorp/terraform:${TERRAFORM_VERSION_TAG}
    volumes:
      - ./${DIR}:/app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  aws:
    working_dir: ${WORKING_DIR:-/app}
    entrypoint: ${ENTRYPOINT}
    build:
      context: .
      dockerfile: Dockerfile.awscli
      args:
        ALPINE_PYTHON_VERSION_TAG: ${ALPINE_PYTHON_VERSION_TAG}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
