---
version: "3.7"

services:
  app:
    working_dir: /app/
    image: tf_and_aws
    entrypoint: ${ENTRYPOINT}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_PYTHON_VERSION_TAG: ${DEBIAN_PYTHON_VERSION_TAG}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION}
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
    volumes:
      - ./terraform:/app
      - ./aws:/root/.aws
